import { AccountDialogs } from "./AccountDialogs";
import { AdminDialogs } from "./AdminDialogs";
import { WorkspaceDialogs } from "./WorkspaceDialogs";

export function OverlayDialogs({
  accountDisplayName,
  session,
  sshKeys,
  joinedContainers,
  activeAccountPanel,
  onCloseAccountPanel,
  sshKeyNameDraft,
  sshKeyDraft,
  onSetSshKeyNameDraft,
  onSetSshKeyDraft,
  sshMessage,
  sshStatus,
  onAddSshKey,
  onDeleteSshKey,
  passwordForm,
  onUpdatePasswordField,
  passwordMessage,
  passwordStatus,
  onChangePassword,
  joinDialogContainer,
  joinDialogAvailableKeys,
  joinDialogSelection,
  joinDialogSelectionUnchanged,
  joinDialogMessage,
  onCloseJoinDialog,
  onToggleJoinDialogKey,
  onConfirmJoinContainer,
  leaveDialogContainer,
  leaveDialogKeys,
  leaveDialogSelection,
  leaveDialogMessage,
  onCloseLeaveDialog,
  onToggleLeaveDialogKey,
  onConfirmLeaveContainer,
  adminUserDialogOpen,
  adminUserForm,
  adminUsersMessage,
  adminUsersStatus,
  onCancelAdminUserEdit,
  onUpdateAdminUserField,
  onSubmitAdminUser,
  adminContainerDialogOpen,
  adminContainerForm,
  adminContainersMessage,
  adminContainersStatus,
  onCancelAdminContainerEdit,
  onUpdateAdminContainerField,
  onSubmitAdminContainer
}) {
  return (
    <>
      <AdminDialogs
        adminUserDialogOpen={adminUserDialogOpen}
        adminUserForm={adminUserForm}
        adminUsersMessage={adminUsersMessage}
        adminUsersStatus={adminUsersStatus}
        onCancelAdminUserEdit={onCancelAdminUserEdit}
        onUpdateAdminUserField={onUpdateAdminUserField}
        onSubmitAdminUser={onSubmitAdminUser}
        adminContainerDialogOpen={adminContainerDialogOpen}
        adminContainerForm={adminContainerForm}
        adminContainersMessage={adminContainersMessage}
        adminContainersStatus={adminContainersStatus}
        onCancelAdminContainerEdit={onCancelAdminContainerEdit}
        onUpdateAdminContainerField={onUpdateAdminContainerField}
        onSubmitAdminContainer={onSubmitAdminContainer}
      />

      <AccountDialogs
        accountDisplayName={accountDisplayName}
        session={session}
        sshKeys={sshKeys}
        joinedContainers={joinedContainers}
        activeAccountPanel={activeAccountPanel}
        onCloseAccountPanel={onCloseAccountPanel}
        sshKeyNameDraft={sshKeyNameDraft}
        sshKeyDraft={sshKeyDraft}
        onSetSshKeyNameDraft={onSetSshKeyNameDraft}
        onSetSshKeyDraft={onSetSshKeyDraft}
        sshMessage={sshMessage}
        sshStatus={sshStatus}
        onAddSshKey={onAddSshKey}
        onDeleteSshKey={onDeleteSshKey}
        passwordForm={passwordForm}
        onUpdatePasswordField={onUpdatePasswordField}
        passwordMessage={passwordMessage}
        passwordStatus={passwordStatus}
        onChangePassword={onChangePassword}
      />

      <WorkspaceDialogs
        sshKeys={sshKeys}
        joinDialogContainer={joinDialogContainer}
        joinDialogAvailableKeys={joinDialogAvailableKeys}
        joinDialogSelection={joinDialogSelection}
        joinDialogSelectionUnchanged={joinDialogSelectionUnchanged}
        joinDialogMessage={joinDialogMessage}
        onCloseJoinDialog={onCloseJoinDialog}
        onToggleJoinDialogKey={onToggleJoinDialogKey}
        onConfirmJoinContainer={onConfirmJoinContainer}
        leaveDialogContainer={leaveDialogContainer}
        leaveDialogKeys={leaveDialogKeys}
        leaveDialogSelection={leaveDialogSelection}
        leaveDialogMessage={leaveDialogMessage}
        onCloseLeaveDialog={onCloseLeaveDialog}
        onToggleLeaveDialogKey={onToggleLeaveDialogKey}
        onConfirmLeaveContainer={onConfirmLeaveContainer}
      />
    </>
  );
}
